### ISSUE TITLE
Baby sea doll sem efeito ao dar use

### ISSUE THREAD

**Issue by FernandoMazeto** [otsolutions/Vanaheim#6]
em otsolutions/Vanaheim/master/data/actions
no arquivo actions.xml
procure por	
Increase/Decrease ItemId -->
e adicione esta linha
-- >        action itemid="7183" function="increaseItemId"

em otsolutions/Vanaheim/master/data/items
no arquivo items.xml
procure por
	item id="7184" article="a" name="baby seal doll"
		<attribute key="weight" value="850" />
	</item>
e troque por
	<item id="7184" article="a" name="baby seal doll">
		<attribute key="weight" value="850" />
		<attribute key="duration" value="3" />
		<attribute key="decayTo" value="7183" />
	</item>

**Comment by FernandoMazeto** [comment]
nao consigo fazer esse issue direito =\

**Comment by Schiffers** [comment]
cara, vc não terminou de falar o que tem que fazer, o que exatamente é pra fazer ?

**Comment by brunominervino** [comment]
Tipo,
Issue você reporta algum bug, ou da alguma sugestão, algo assim.
Caso você queira fazer alguma correção você mesmo, de um fork no projeto e faz um pull request.
Ai você também entra como um contribuidor ^^

Caso não saiba como, procure algum tutorial no google, é bem simples!
Att.
