### ISSUE TITLE
Killing In The Name Of... Quest

### ISSUE THREAD

**Issue by RafaelPereiraa** [otsolutions/Vanaheim#8]
Impossível de entregar task de tarantulas/ter acesso ao boss Hide. Não sei as outras tasks pois ainda não testei.

**Comment by brunominervino** [comment]
Você tentou entregar a task falando **report**?

**Comment by RafaelPereiraa** [comment]
É, não tentei... tentei procurar as possíveis falas do npc mas não entendi ainda direito como funciona a hierarquia dos arquivos... chegando em casa vou testar, mas deve ter sido isso então. Desculpe.

**Comment by RafaelPereiraa** [comment]
Eu que me equivoquei, realmente está funcionando com o Report.
Obrigado, Bruno.

**Comment by brunominervino** [comment]
Sem problemas man!
